Repository wecode-bootcamp-korea/44-2nd-Dream-backend, pull requests merged in 2023-05, with the labels that each got.

#20 [44기 장다희] ADD: 입찰 기능 구현
  API/controllers/bidController.js
  API/models/bidDao.js
  API/routes/bidRouter.js
  API/routes/index.js
  API/services/bidService.js
Labels: 완료

#21 [44기 김민서][ADD]feature/review
  API/controllers/reviewController.js
  API/models/reviewDao.js
  API/routes/index.js
  API/routes/reviewRouter.js
  API/services/reviewService.js
  API/utils/s3.js
  package-lock.json
  package.json
Labels: 완료

#24 [44기 박세익] FIX: feature/socialLogin 수정
  API/controllers/userController.js
  API/services/userService.js
Labels: 완료

#17 [44기 김민서][ADD]likeCreate
  API/controllers/likeController.js
  API/controllers/productController.js
  API/models/likeDao.js
  API/models/productDao.js
  API/routes/index.js
  API/routes/likeRouter.js
  API/routes/productRouter.js
  API/services/likeService.js
  API/services/productService.js
  tests/fixtures/products-fixture.js
  tests/tests/likes.test.js
  tests/tests/products.test.js
Labels: Conflict 해결 요청

#23 [44기 박세익] ADD: feature/review"R", "D"
  API/controllers/reviewController.js
  API/models/reviewDao.js
  API/routes/index.js
  API/routes/reviewRouter.js
  API/services/reviewService.js
Labels: 완료

#25 [44기 장다희] FIX: 다음 페이지에서 필요한 property를 resonse에 추가
  API/services/bidService.js
Labels: 완료

#7 [44기 송석준][ADD]search 기능 구현
  API/controllers/productController.js
  API/controllers/searchController.js
  API/models/searchDao.js
  API/routes/index.js
  API/routes/searchRouter.js
  API/services/searchService.js
  tests/tests/search.test.js
Labels: 완료

#28 [44기 장다희] ADD: 인기검색어 조회 기능 구현
  API/controllers/reviewController.js
  API/controllers/searchController.js
  API/models/searchDao.js
  API/routes/index.js
  API/routes/searchRouter.js
  API/services/searchService.js
  app.js
  db/migrations/20230430152827_search_keywords.sql
Labels: 완료

#22 [44기 송석준][ADD] feature/reviewUpdate
  API/controllers/reviewController.js
  API/models/reviewDao.js
  API/routes/index.js
  API/routes/reviewRouter.js
  API/services/reviewService.js
  package-lock.json
  package.json
Labels: 완료

#29 [44기 김민서][FIX]bid info
  API/services/bidService.js
Labels: 완료

#31 [44기 장다희] ADD: account number & card number 저장/조회 기능
  API/controllers/userController.js
  API/models/userDao.js
  API/routes/userRouter.js
  API/services/userService.js
Labels: 완료

#33 [44기 장다희] ADD: 입찰 진행 페이지 정보 요청 기능 구현
  API/controllers/bidController.js
  API/models/appDataSource.js
  API/models/bidDao.js
  API/routes/bidRouter.js
  API/services/bidService.js
Labels: 완료

#34 [44기 김민서][fix] buybidding AND review 조건 변경
  API/controllers/paymentController.js
  API/controllers/userController.js
  API/models/paymentDao.js
  API/models/reviewDao.js
  API/routes/paymentRouter.js
  API/routes/productRouter.js
  API/services/paymentService.js
  API/services/reviewService.js
  API/services/userService.js
  API/utils/auth.js
Labels: 완료

#35 [44기 김민서][fix]like
  API/models/productDao.js
Labels: 완료

#36 [44기 김민서][fix]like List
  API/models/productDao.js
Labels: 완료

#16 [44기 박세익][ADD] Feature/Process_Payment_Info
  API/controllers/paymentController.js
  API/models/enum.js
  API/models/paymentDao.js
  API/models/reviewDao.js
  API/routes/index.js
  API/routes/paymentRouter.js
  API/services/paymentService.js
  API/services/userService.js
  db/migrations/20230502062933_addcolumn_to_sellings.sql
Labels: 완료

#37 [44기 team_DREAM]REFACT: 전체적인 컨벤션 통일
  API/controllers/bidController.js
  API/controllers/likeController.js
  API/controllers/paymentController.js
  API/controllers/productController.js
  API/controllers/reviewController.js
  API/controllers/searchController.js
  API/controllers/userController.js
  API/models/bidDao.js
  API/models/likeDao.js
  API/models/paymentDao.js
  API/models/productDao.js
  API/models/reviewDao.js
  API/models/searchDao.js
  API/models/userDao.js
  API/routes/bidRouter.js
  API/routes/index.js
  API/routes/likeRouter.js
  API/routes/paymentRouter.js
  API/routes/productRouter.js
  API/routes/reviewRouter.js
  API/routes/searchRouter.js
  API/routes/userRouter.js
  API/services/bidService.js
  API/services/likeService.js
  API/services/paymentService.js
  API/services/productService.js
  API/services/reviewService.js
  API/services/searchService.js
  API/services/userService.js
  API/utils/auth.js
  API/utils/bidStatusScheduler.js
  API/utils/error.js
  server.js
Labels: 완료

#38 [44기 박세익] Fix : feature/payment
  API/controllers/paymentController.js
  API/models/paymentDao.js
Labels: 완료

#39 [44기 장다희] FIX: 인기 검색어 기능 에러 수정
  API/models/searchDao.js
Labels: 멘토 리뷰 요청
